# prettier-ignore
version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    # restart: always
    networks: 
      - db-network

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   # restart: always
  #   networks: 
  #     - db-network

  pgaadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: aaa@domain.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8080:80
    networks: 
      - db-network

volumes:
  postgres_data:
    external: true

networks: 
  db-network:
