version: '3'
services:
  budbudget.rest:
    image: ${REGISTRY_LOGIN_SERVER}/budbudget.rest:${TAG:-latest}
    ports:
      - 5000:5000
    environment:
      PGSQL_HOST: ${PGSQL_HOST:-postgres}
      PGSQL_PORT: ${PGSQL_PORT:-5432}
      PGSQL_DATABASE: ${PGSQL_DATABASE:-postgres}
      PGSQL_USERNAME: ${PGSQL_USERNAME:-postgres}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD:-postgres}
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devcert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345678
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      USE_COOKIE_AUTH: "false"
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE:-postgres}
      POSTGRES_USER: ${PGSQL_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD:-postgres}
      restart: always
