# prettier-ignore
version: '3'
services:
  budbudget.rest:
    image: budbudget.rest
    build: 
      context: ./BudBudget.REST
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    environment:
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      PGSQL_DATABASE: postgres
      PGSQL_USERNAME: postgres
      PGSQL_PASSWORD: postgres
      APPLICATIONURLS: http://0.0.0.0:5000 # Set the port here for the server. Don't change the ip
      ASPNETCORE_ENVIRONMENT: Production
    networks: 
      - db-network

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - db-network

volumes:
  postgres_data:
    external: true

networks: 
  db-network:
