version: '3'
services:
  budbudget.rest:
    image: ${REGISTRY_LOGIN_SERVER}/budbudget.rest:${TAG:-latest}
    environment:
      PGSQL_HOST: ${PGSQL_HOST:-postgres}
      PGSQL_PORT: ${PGSQL_PORT:-5432}
      PGSQL_DATABASE: ${PGSQL_DATABASE:-postgres}
      PGSQL_USERNAME: ${PGSQL_USERNAME:-postgres}
      PGSQL_PASSWORD: ${PGSQL_PASSWORD:-postgres}
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devcert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345678
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      USE_COOKIE_AUTH: "false"
      
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE:-postgres}
      POSTGRES_USER: ${PGSQL_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD:-postgres}
      restart: always
      
  budbudget.web:
    image: ${REGISTRY_LOGIN_SERVER}/budbudget.web:${TAG:-latest}      
    
  # Reverse proxy for Let's Encrypt
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx_data/nginx:/etc/nginx/conf.d
      - ./nginx_data/certbot/conf:/etc/letsencrypt
      - ./nginx_data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx_data/certbot/conf:/etc/letsencrypt
      - ./nginx_data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
