# prettier-ignore
version: '3'
services:
  budbudget.rest:
    image: budbudget.rest
    build: 
      context: ./BudBudget.REST
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    environment:
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      PGSQL_DATABASE: postgres
      PGSQL_USERNAME: postgres
      PGSQL_PASSWORD: postgres
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/devcert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345678
      ASPNETCORE_ENVIRONMENT: Production
    networks: 
      - db-network

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - db-network

volumes:
  postgres_data:
    external: true

networks: 
  db-network:
