# prettier-ignore
version: '3'
services:
  budbudget.vscode:
    image: budbudget.vscode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - ..:/workspace
    command: /bin/sh -c "cd /workspace/BudBudget.WEB; yarn start"
    environment:
      PGSQL_HOST: postgres
      PGSQL_PORT: 5432
      PGSQL_DATABASE: postgres
      PGSQL_USERNAME: postgres
      PGSQL_PASSWORD: postgres
      APPLICATIONURLS: http://0.0.0.0:5000 # Set the port for the server. Don't change the ip 0.0.0.0
      ASPNETCORE_ENVIRONMENT: Development
    networks: 
      - db-network

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: aaa@domain.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8080:80
    networks: 
      - db-network

volumes:
  postgres_data:
    external: true

networks: 
  db-network:
