# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-and-publish-backend:
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd BudBudget.REST
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/budbudget.rest:${{ github.run_number}}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/budbudget.rest:${{ github.run_number}}

  build-and-publish-web:
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
      - run: |
          cd BudBudget.WEB
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/budbudget.web:${{ github.run_number}} --build-arg API_BASE_URL=${{ env.API_BASE_URL }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/budbudget.web:${{ github.run_number}}
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-publish-backend,build-and-publish-web]
    env:
        PGSQL_HOST: ${{ secrets.PGSQL_HOST }}
        PGSQL_DATABASE: ${{ secrets.PGSQL_DATABASE }}
        PGSQL_USERNAME: ${{ secrets.PGSQL_USERNAME }}
        PGSQL_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
        ASPNETCORE_ENVIRONMENT: Development
        REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        TAG: ${{ github.run_number }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      
    - name: Copy docker-compose
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.DOCKER_USERNAME }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        source: "docker-compose.azure.yml"
        target: "~/budbudget/"
      
    - name: Deploy docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.DOCKER_USERNAME }}
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        #envs: REGISTRY_LOGIN_SERVER,PGSQL_HOST,PGSQL_DATABASE,PGSQL_USERNAME,PGSQL_PASSWORD,ASPNETCORE_ENVIRONMENT
        script: |
          export PGSQL_HOST=${{ env.PGSQL_HOST }}
          export PGSQL_DATABASE=${{ env.PGSQL_DATABASE }}
          export PGSQL_USERNAME=${{ env.PGSQLUSERNAME }}
          export PGSQL_PASSWORD=${{ env.PGSQLPASSWORD }}
          export REGISTRY_LOGIN_SERVER=${{ env.REGISTRY_LOGIN_SERVER }}
          export ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}
          export TAG=${{ env.TAG }}
          docker login --username ${{ secrets.REGISTRY_USERNAME}} --password ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_LOGIN_SERVER }}
          cd ~/budbudget
          docker-compose -f docker-compose.azure.yml down
          docker-compose -f docker-compose.azure.yml up -d
