# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build back end image
        run: |
          cd BudBudget.REST
          docker build -t budbudget.rest .
          
      - name: Deploy image
        run: >
          docker run -d -p 80:5000
          -e PGSQL_HOST=localhost
          -e ASPNETCORE_URLS=http://+:5000
          -e ASPNETCORE_ENVIRONMENT=Development
          budbudget.rest:latest
